# Generated by Django 4.1.1 on 2022-10-07 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, default='')),
                ('link', models.TextField()),
                ('region_info', models.JSONField()),
                ('thumbnail_filename', models.TextField()),
            ],
            options={
                'db_table': 'snapshots',
            },
        ),
    ]
