# Generated by Django 4.1.1 on 2022-10-14 19:20

from django.db import migrations, models
import django.db.models.deletion

from PIL import Image
from base.settings import MEDIA_ROOT

from lib.image_manipulation import make_thumbnail
from social.actions.snapshot_images import snapshot_to_thumbnail_filename


THUMBNAIL_SIZES = [
    (100, 100),
    (320, 180),
    (960, 540),
]

def fix_existing_snapshots(apps, schema_editor):
    Snapshot = apps.get_model('social', 'Snapshot')
    Thumbnail = apps.get_model('social', 'Thumbnail')

    for snapshot in Snapshot.objects.all():
        original_filename = f'snapshot-id-{snapshot.id}--original.png'
        original_img = Image.open(MEDIA_ROOT / original_filename)

        original_thumbnail = Thumbnail(
            snapshot=snapshot,
            is_original=True,
            filename=original_filename,
            width=original_img.width,
            height=original_img.height,
        )
        original_thumbnail.save()

        for size in THUMBNAIL_SIZES:
            width, height = size
            thumbnail_img = make_thumbnail(original_img, size)
            filename = snapshot_to_thumbnail_filename(snapshot, size)
            thumbnail_img.save(MEDIA_ROOT / filename)

            thumbnail = Thumbnail(
                snapshot=snapshot,
                is_original=False,
                filename=filename,
                width=width,
                height=height,
            )
            thumbnail.save()


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snapshot',
            name='thumbnail_filename',
        ),
        migrations.CreateModel(
            name='Thumbnail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('filename', models.TextField()),
                ('is_original', models.BooleanField()),
                ('height', models.IntegerField()),
                ('width', models.IntegerField()),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='thumbnails', to='social.snapshot')),
            ],
            options={
                'db_table': 'thumbnails',
            },
        ),
        migrations.RunPython(
            fix_existing_snapshots,
            lambda apps, schema_editor: None,
        ),
    ]
