# Generated by Django 4.1.1 on 2022-12-24 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, default='')),
                ('link', models.TextField()),
                ('region_info', models.JSONField()),
            ],
            options={
                'db_table': 'snapshots',
            },
        ),
        migrations.CreateModel(
            name='Thumbnail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('filename', models.TextField()),
                ('is_original', models.BooleanField()),
                ('height', models.IntegerField()),
                ('width', models.IntegerField()),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='thumbnails', to='social.snapshot')),
            ],
            options={
                'db_table': 'thumbnails',
            },
        ),
    ]
