# Generated by Django 4.1.1 on 2022-12-25 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def set_snapshot_author_id(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Snapshot = apps.get_model('social', 'Snapshot')
    User = apps.get_model('social', 'User')

    dan = User.objects.using(db_alias).filter(username='dan').first()
    Snapshot.objects.using(db_alias).all().update(author_id=dan.id)

def set_snapshot_author_to_null(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Snapshot = apps.get_model('social', 'Snapshot')
    Snapshot.objects.using(db_alias).all().update(author_id=None)


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_snapshot_thumbnail'),
    ]

    operations = [
        # Initially, need to allow author_id to be NULL, as we have existing data
        migrations.AddField(
            model_name='snapshot',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='snapshots', to=settings.AUTH_USER_MODEL),
        ),

        # Set author_id to a meaningful non-NULL value
        migrations.RunPython(
            set_snapshot_author_id,
            set_snapshot_author_to_null,
        ),

        # Update author_id to be non-nullable
        migrations.AlterField(
            model_name='snapshot',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='snapshots', to=settings.AUTH_USER_MODEL),
        ),
    ]
