# Generated by Django 4.1.1 on 2023-02-15 06:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_snapshot_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='SnapshotLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='social.snapshot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'snapshot_likes',
            },
        ),
        migrations.AddField(
            model_name='snapshot',
            name='liked_by',
            field=models.ManyToManyField(related_name='liked_snapshots', through='social.SnapshotLike', to=settings.AUTH_USER_MODEL),
        ),
    ]
